development:
  sessions:
    default:
      database: mydb
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>

